apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kzdroe.fullname" . }}
  labels:
    {{- include "kzdroe.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kzdroe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kzdroe.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kzdroe.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.metrics.nginx.enabled }}
        - name: nginx-metrics
          image: "{{ .Values.metrics.nginx.image.repository }}:{{ .Values.metrics.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.nginx.image.pullPolicy | quote }}
          command: ['/usr/bin/exporter', '-nginx.scrape-uri', 'http://127.0.0.1:9532/metrics']
          ports:
            - name: nginx-metrics
              containerPort: 9113
          livenessProbe:
            httpGet:
              path: /metrics
              port: nginx-metrics
            initialDelaySeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: nginx-metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          {{- if .Values.metrics.nginx.resources }}
          resources: {{- toYaml .Values.metrics.nginx.resources | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.metrics.uwsgi.enabled }}
        - name: uwsgi-metrics
          image: "{{ .Values.metrics.uwsgi.image.repository }}:{{ .Values.metrics.uwsgi.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.uwsgi.image.pullPolicy | quote }}
          args: ["--stats.uri", "tcp://localhost:1717"]
          ports:
            - name: uwsgi-metrics
              containerPort: 9117
          livenessProbe:
            httpGet:
              path: /metrics
              port: uwsgi-metrics
            initialDelaySeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: uwsgi-metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          {{- if .Values.metrics.uwsgi.resources }}
          resources: {{- toYaml .Values.metrics.uwsgi.resources | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
