{{- if and (or .Values.kzdroe.s3.accessKey .Values.kzdroe.s3.secretKey) (not (and .Values.kzdroe.s3.accessKey .Values.kzdroe.s3.secretKey)) -}}
{{ fail "S3: If providing credentials, accessKey and secretKey must be both set." }}
{{- end -}}

{{- if and .Values.kzdroe.s3.enabled .Values.kzdroe.s3.accessKey .Values.kzdroe.s3.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kzdroe.fullname" . }}-s3
  labels:
    {{- include "kzdroe.labels" . | nindent 4 }}
type: Opaque
data:
  S3_ACCESS_KEY: {{ .Values.kzdroe.s3.accessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.kzdroe.s3.secretKey | b64enc | quote }}
  S3_HOST: {{ .Values.kzdroe.s3.endpointUrl | b64enc | quote }}
{{- end }}